# Generated by Django 5.2.3 on 2025-06-29 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bases', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaseModelo2',
        ),
    ]
