# Generated by Django 5.2.3 on 2025-06-29 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bases', '0002_delete_clasemodelo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
            ],
            options={
                'verbose_name_plural': 'Idiomas',
            },
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autor', models.CharField(default='Anónimo', max_length=70)),
                ('frase', models.TextField(blank=True, null=True)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bases.idioma')),
            ],
            options={
                'verbose_name_plural': 'Frases',
            },
        ),
    ]
